
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 07 02:21:19 CLST 2016
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSEBRACKETLL = 28;
  public static final int ROOT = 16;
  public static final int OPENBRACKETCOR = 27;
  public static final int SUBT = 5;
  public static final int ELSE = 10;
  public static final int INT = 2;
  public static final int MAYEQ = 20;
  public static final int WHILE = 11;
  public static final int OPENBRACKETLL = 26;
  public static final int RETURN = 14;
  public static final int MINEQ = 18;
  public static final int IF = 9;
  public static final int POT = 15;
  public static final int ID = 33;
  public static final int NUM = 32;
  public static final int CLOSEBRACKETCOR = 29;
  public static final int COMA = 30;
  public static final int STRING = 3;
  public static final int MAYOR = 19;
  public static final int EOF = 0;
  public static final int MULT = 7;
  public static final int PUNTUACTION = 24;
  public static final int DIV = 6;
  public static final int COMMENT = 31;
  public static final int ADD = 4;
  public static final int MINOR = 17;
  public static final int error = 1;
  public static final int CLOSEBRACKET = 25;
  public static final int OPENBRACKET = 23;
  public static final int EQ = 21;
  public static final int ASSIGN = 8;
  public static final int FOR = 12;
  public static final int NEQ = 22;
  public static final int VOID = 13;
}

